/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-09 08:04:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Patient;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxnu.entity.Doctor;
import java.util.List;
import com.gxnu.service.imp.DoctorService;
import com.gxnu.service.IDoctorService;
import com.gxnu.util.Data;

public final class Doctor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gxnu.util.Data");
    _jspx_imports_classes.add("com.gxnu.service.imp.DoctorService");
    _jspx_imports_classes.add("com.gxnu.entity.Doctor");
    _jspx_imports_classes.add("com.gxnu.service.IDoctorService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Meta Tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"keywords\" content=\"Site keywords here\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name='copyright' content=''>\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<!-- Title -->\r\n");
      out.write("<title>医生信息</title>\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"icon\" href=\"img/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<!-- Nice Select CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/nice-select.css\">\r\n");
      out.write("<!-- Font Awesome CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<!-- icofont CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icofont.css\">\r\n");
      out.write("<!-- Slicknav -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/slicknav.min.css\">\r\n");
      out.write("<!-- Owl Carousel CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl-carousel.css\">\r\n");
      out.write("<!-- Datepicker CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/datepicker.css\">\r\n");
      out.write("<!-- Animate CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.min.css\">\r\n");
      out.write("<!-- Magnific Popup CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Medipro CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/normalize.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Breadcrumbs -->\r\n");
      out.write("\t<div class=\"breadcrumbs overlay\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"bread-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t<h2>医生</h2>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"bread-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.html\">科室</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"icofont-simple-right\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\">医生信息</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Breadcrumbs -->\r\n");
      out.write("\t");

		IDoctorService doctorService = new DoctorService();
		List<Doctor> doctors = doctorService.find();
		for (Doctor doctor : doctors) {
	
      out.write("\r\n");
      out.write("\t<!-- Doctor Details -->\r\n");
      out.write("\t<div class=\"doctor-details-area section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!--修改图片 改变尺寸请修改col-lg-?语句-->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"doctor-details-item doctor-details-left\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(Data.URL);
      out.write('/');
      out.print(doctor.getPic());
      out.write("\" alt=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"doctor-details-contact\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>相关信息</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"basic-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"icofont-ui-call\"></i> 电话 : ");
      out.print(doctor.getTel() );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"icofont-ui-message\"></i> 邮箱：");
      out.print(doctor.getEmail() );
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"doctor-details-work\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>工作时间</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"time-sidual\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"day\">星期一 - 星期五 <span>8.00-20.00</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"day\">星期四 <span>9.00-18.30</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"day\">星期一 - 星期四 <span>9.00-15.00</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"day\">星期一 - 星期三 <span>8.00-20.00</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-7\">\r\n");
      out.write("\t\t\t\t\t<div class=\"doctor-details-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"doctor-details-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"doctor-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"name\">医生姓名：");
      out.print(doctor.getName() );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"deg\">性别：");
      out.print(doctor.getSex() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"deg\">年龄：");
      out.print(doctor.getAge() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"doctor-details-biography\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>所在科室</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>");
      out.print(doctor.getUnit().getName() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>儿科是全面研究小儿时期身心发育、保健以及疾病防治的综合医学科学。 凡涉及 儿童 和 青少年 时期的健康与卫生问题都属于儿科范围。 其医治的对象处于生长发育期。</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"doctor-details-biography\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>职位</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>");
      out.print(doctor.getPost().getPost() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Doctor Details -->\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- jquery Min JS -->\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jquery Migrate JS -->\r\n");
      out.write("\t<script src=\"js/jquery-migrate-3.0.0.js\"></script>\r\n");
      out.write("\t<!-- jquery Ui JS -->\r\n");
      out.write("\t<script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<!-- Easing JS -->\r\n");
      out.write("\t<script src=\"js/easing.js\"></script>\r\n");
      out.write("\t<!-- Color JS -->\r\n");
      out.write("\t<script src=\"js/colors.js\"></script>\r\n");
      out.write("\t<!-- Popper JS -->\r\n");
      out.write("\t<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap Datepicker JS -->\r\n");
      out.write("\t<script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t<!-- Jquery Nav JS -->\r\n");
      out.write("\t<script src=\"js/jquery.nav.js\"></script>\r\n");
      out.write("\t<!-- Slicknav JS -->\r\n");
      out.write("\t<script src=\"js/slicknav.min.js\"></script>\r\n");
      out.write("\t<!-- ScrollUp JS -->\r\n");
      out.write("\t<script src=\"js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("\t<!-- Niceselect JS -->\r\n");
      out.write("\t<script src=\"js/niceselect.js\"></script>\r\n");
      out.write("\t<!-- Tilt Jquery JS -->\r\n");
      out.write("\t<script src=\"js/tilt.jquery.min.js\"></script>\r\n");
      out.write("\t<!-- Owl Carousel JS -->\r\n");
      out.write("\t<script src=\"js/owl-carousel.js\"></script>\r\n");
      out.write("\t<!-- counterup JS -->\r\n");
      out.write("\t<script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("\t<!-- Steller JS -->\r\n");
      out.write("\t<script src=\"js/steller.js\"></script>\r\n");
      out.write("\t<!-- Wow JS -->\r\n");
      out.write("\t<script src=\"js/wow.min.js\"></script>\r\n");
      out.write("\t<!-- Magnific Popup JS -->\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<!-- Counter Up CDN JS -->\r\n");
      out.write("\t<script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap JS -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Main JS -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
