/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-09 12:03:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Patient;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PersonInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<title>无标题文档</title>\r\n");
      out.write("\t\t<!-- Favicon -->\r\n");
      out.write("        <link rel=\"icon\" href=\"img/favicon.png\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Google Fonts -->\r\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bootstrap CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t\t<!-- Nice Select CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/nice-select.css\">\r\n");
      out.write("\t\t<!-- Font Awesome CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("\t\t<!-- icofont CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/icofont.css\">\r\n");
      out.write("\t\t<!-- Slicknav -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/slicknav.min.css\">\r\n");
      out.write("\t\t<!-- Owl Carousel CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/owl-carousel.css\">\r\n");
      out.write("\t\t<!-- Datepicker CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/datepicker.css\">\r\n");
      out.write("\t\t<!-- Animate CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/animate.min.css\">\r\n");
      out.write("\t\t<!-- Magnific Popup CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Medipro CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/normalize.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Color CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/color/color1.css\">\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color2.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color3.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color4.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color5.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color6.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color7.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color8.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color9.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color10.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color11.css\">-->\r\n");
      out.write("\t\t<!--<link rel=\"stylesheet\" href=\"css/color/color12.css\">-->\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"#\" id=\"colors\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \r\n");
      out.write("<body style=\"overflow:hidden\">\r\n");
      out.write("<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"171\" id=frmTitle noWrap name=\"fmTitle\" align=\"center\" valign=\"top\"><table width=\"171\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td  bgcolor=\"#1873aa\" style=\"width:6px;\">&nbsp;</td>\r\n");
      out.write("        <td width=\"165\"><iframe name=\"I1\" height=\"100%\" width=\"165\" src=\"left.html\" border=\"0\" frameborder=\"0\" scrolling=\"no\"> 浏览器不支持嵌入式框架，或被配置为不显示嵌入式框架。</iframe></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\t\t</td>\r\n");
      out.write("    <td width=\"6\"  style=\"width:6px;\"valign=\"middle\" bgcolor=\"1873aa\" onclick=switchSysBar()><SPAN class=navPoint \r\n");
      out.write("id=switchPoint title=关闭/打开左栏><img src=\"images/main_55.gif\" name=\"img1\" width=6 height=40 id=img1></SPAN></td>\r\n");
      out.write("    <td width=\"100%\" align=\"center\" valign=\"top\"><iframe name=\"I2\" height=\"100%\" width=\"100%\" border=\"0\" frameborder=\"0\" src=\"tab/tab.html\"> 浏览器不支持嵌入式框架，或被配置为不显示嵌入式框架。</iframe></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table> -->\r\n");
      out.write("\t<!-- Preloader -->\r\n");
      out.write("        <div class=\"preloader\">\r\n");
      out.write("            <div class=\"loader\">\r\n");
      out.write("                <div class=\"loader-outter\"></div>\r\n");
      out.write("                <div class=\"loader-inner\"></div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"indicator\"> \r\n");
      out.write("                    <svg width=\"16px\" height=\"12px\">\r\n");
      out.write("                        <polyline id=\"back\" points=\"1 6 4 6 6 11 10 1 12 6 15 6\"></polyline>\r\n");
      out.write("                        <polyline id=\"front\" points=\"1 6 4 6 6 11 10 1 12 6 15 6\"></polyline>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Preloader -->\r\n");
      out.write("\t\t<!-- Breadcrumbs -->\r\n");
      out.write("\t\t<div class=\"breadcrumbs overlay\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"bread-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>个人信息修改</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"bread-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"index.html\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><i class=\"icofont-simple-right\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"active\">个人信息修改</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End Breadcrumbs -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- Shop Register -->\r\n");
      out.write("\t\t<section class=\"register section\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\"> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"register-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>个人信息修改</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>如果想修改密码，<a href=\"login.html\">请点击这里</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Form -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"form\" method=\"post\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" placeholder=\"姓名\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" placeholder=\"年龄\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" placeholder=\"联系电话\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" placeholder=\"邮箱\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" placeholder=\"修改头像\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group login-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\">确定修改</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--/ End Form -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!--/ End Register -->\r\n");
      out.write("\t\t<!-- \r\n");
      out.write("\t\tFooter Area\r\n");
      out.write("\t\t<footer id=\"footer\" class=\"footer \">\r\n");
      out.write("\t\t\tFooter Top\r\n");
      out.write("\t\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>About Us</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit am consectetur adipisicing elit do eiusmod tempor incididunt ut labore dolore magna.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\tSocial\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icofont-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icofont-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icofont-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icofont-vimeo\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"icofont-pinterest\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\tEnd Social\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-footer f-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Quick Links</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>Our Cases</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>Other Links</a></li>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>Consuling</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>Finance</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>Testimonials</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-caret-right\" aria-hidden=\"true\"></i>Contact Us</a></li>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Open Hours</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit ame consectetur adipisicing elit do eiusmod tempor incididunt.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"time-sidual\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"day\">Monday - Fridayp <span>8.00-20.00</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"day\">Saturday <span>9.00-18.30</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"day\">Monday - Thusday <span>9.00-15.00</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Newsletter</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>subscribe to our newsletter to get allour news in your inbox.. Lorem ipsum dolor sit amet, consectetur adipisicing elit,</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"mail/mail.php\" method=\"get\" target=\"_blank\" class=\"newsletter-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"email\" placeholder=\"Email Address\" class=\"common-input\" onfocus=\"this.placeholder = ''\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"this.placeholder = 'Your email address'\" required=\"\" type=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"button\"><i class=\"icofont icofont-paper-plane\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t/ End Footer Top\r\n");
      out.write("\t\t\tCopyright\r\n");
      out.write("\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12 col-md-12 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"copyright-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Copyright &copy; 2020.Company name All rights reserved.<a target=\"_blank\" href=\"http://sc.chinaz.com/moban/\">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t/ End Copyright\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t/ End Footer Area\r\n");
      out.write("\t\t -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- jquery Min JS -->\r\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<!-- jquery Migrate JS -->\r\n");
      out.write("\t\t<script src=\"js/jquery-migrate-3.0.0.js\"></script>\r\n");
      out.write("\t\t<!-- jquery Ui JS -->\r\n");
      out.write("\t\t<script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t\t<!-- Easing JS -->\r\n");
      out.write("        <script src=\"js/easing.js\"></script>\r\n");
      out.write("\t\t<!-- Color JS -->\r\n");
      out.write("\t\t<script src=\"js/colors.js\"></script>\r\n");
      out.write("\t\t<!-- Popper JS -->\r\n");
      out.write("\t\t<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("\t\t<!-- Bootstrap Datepicker JS -->\r\n");
      out.write("\t\t<script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t\t<!-- Jquery Nav JS -->\r\n");
      out.write("        <script src=\"js/jquery.nav.js\"></script>\r\n");
      out.write("\t\t<!-- Slicknav JS -->\r\n");
      out.write("\t\t<script src=\"js/slicknav.min.js\"></script>\r\n");
      out.write("\t\t<!-- ScrollUp JS -->\r\n");
      out.write("        <script src=\"js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("\t\t<!-- Niceselect JS -->\r\n");
      out.write("\t\t<script src=\"js/niceselect.js\"></script>\r\n");
      out.write("\t\t<!-- Tilt Jquery JS -->\r\n");
      out.write("\t\t<script src=\"js/tilt.jquery.min.js\"></script>\r\n");
      out.write("\t\t<!-- Owl Carousel JS -->\r\n");
      out.write("        <script src=\"js/owl-carousel.js\"></script>\r\n");
      out.write("\t\t<!-- counterup JS -->\r\n");
      out.write("\t\t<script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("\t\t<!-- Steller JS -->\r\n");
      out.write("\t\t<script src=\"js/steller.js\"></script>\r\n");
      out.write("\t\t<!-- Wow JS -->\r\n");
      out.write("\t\t<script src=\"js/wow.min.js\"></script>\r\n");
      out.write("\t\t<!-- Magnific Popup JS -->\r\n");
      out.write("\t\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t\t<!-- Counter Up CDN JS -->\r\n");
      out.write("\t\t<script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("\t\t<!-- Bootstrap JS -->\r\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<!-- Main JS -->\r\n");
      out.write("\t\t<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
