/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-10 08:23:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Doctor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;
import com.gxnu.util.Data;
import java.text.SimpleDateFormat;
import com.gxnu.service.imp.DoctorService;
import com.gxnu.entity.Doctor;
import com.gxnu.service.IDoctorService;
import com.gxnu.entity.Patient;
import com.gxnu.service.imp.PatientService;
import com.gxnu.service.IPatientService;

public final class addRecord_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxnu.util.Data");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("com.gxnu.service.imp.DoctorService");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.gxnu.entity.Doctor");
    _jspx_imports_classes.add("com.gxnu.service.IDoctorService");
    _jspx_imports_classes.add("com.gxnu.service.IPatientService");
    _jspx_imports_classes.add("com.gxnu.entity.Patient");
    _jspx_imports_classes.add("com.gxnu.service.imp.PatientService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>:: 填写病例表::  添加病例 </title>\r\n");
      out.write("    <!-- project css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/ihealth.style.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("    <!-- 医生信息从登录信息获取，患者信息从预约情况获取 -->\r\n");

	IPatientService patientService = new PatientService();
	int patientId = Integer.parseInt(request.getParameter("patientId"));
	Patient patient = patientService.find(patientId);
	
	IDoctorService doctorService = new DoctorService();
	int doctorId = Integer.parseInt(request.getParameter("doctorId"));
	Doctor doctor = doctorService.find(doctorId);
    
    Calendar calendar= Calendar.getInstance();
    SimpleDateFormat dateFormat= new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    System.out.println(dateFormat.format(calendar.getTime()));
    
      out.write("\r\n");
      out.write("<script >\r\n");
      out.write("\tfunction tj(){\r\n");
      out.write("\t\twindow.document.getElementById(\"frm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"ihealth-layout\" class=\"theme-tradewind\">\r\n");
      out.write("  <div class=\"main px-lg-4 px-md-4\">\r\n");
      out.write("      <!-- Body: Body -->\r\n");
      out.write("        <div class=\"body d-flex py-3\">\r\n");
      out.write("            <div class=\"container-xxl\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"border-0 mb-4\">\r\n");
      out.write("                        <div class=\"card-header py-3 no-bg bg-transparent d-flex align-items-center px-0 justify-content-between border-bottom flex-wrap\">\r\n");
      out.write("                            <h3 class=\"fw-bold mb-0\">填写病例</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> <!-- Row end  -->\r\n");
      out.write("                <div class=\"row mb-3\">\r\n");
      out.write("                    <div class=\"col-sm-12\">\r\n");
      out.write("                        <div class=\"card mb-3\">\r\n");
      out.write("                            <div class=\"card-header py-3 d-flex justify-content-between bg-transparent border-bottom-0\">\r\n");
      out.write("                                <h6 class=\"mb-0 fw-bold \">填写病例</h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <form id=\"frm\" action=\"");
      out.print(Data.URL);
      out.write("/record?OP=add\" method=\"post\">\r\n");
      out.write("                                <div class=\"col-md-6\">\r\n");
      out.write("                                            <label for=\"firstname\" class=\"mb-0 fw-bold \">患者信息</label>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                    <div class=\"row g-3 align-items-center\">          \r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label for=\"firstname\" class=\"form-label\">姓名：");
      out.print(patient.getName());
      out.write("</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label class=\"form-label\">性别：");
      out.print(patient.getSex() );
      out.write("</label>                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                                   \r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label for=\"admitdate\" class=\"form-label\">年龄：");
      out.print(patient.getAge());
      out.write("></label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"row g-3 align-items-center\">                                     \r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label for=\"phonenumber\" class=\"mb-0 fw-bold \">症状描述</label>                    \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                   \t\t<textarea  name=\"disease\" rows=\"10\"required=\"\"></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                         <div class=\"row g-3 align-items-center\">   \r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label for=\"emailaddress\" class=\"mb-0 fw-bold \">诊断结果</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                         <textarea  name=\"result\" rows=\"10\"required=\"\"></textarea>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                       <div class=\"row g-3 align-items-center\">  \r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                            <label for=\"admittime\" class=\"form-label\">主治医生：");
      out.print(doctor.getName() );
      out.write("</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                         <div class=\"row g-3 align-items-center\">   \r\n");
      out.write("                                        <div class=\"col-md-6\">\r\n");
      out.write("                                     <input type=\"hidden\" name=\"patientid\" value=\"");
      out.print(patient.getId() );
      out.write("\"/> \r\n");
      out.write("                                       <input type=\"hidden\" name=\"doctorid\" value=\"");
      out.print(doctor.getId());
      out.write("\"/>\r\n");
      out.write("                                       <input type=\"hidden\" name=\"time\" value=\"");
      out.print(dateFormat.format(calendar.getTime()));
      out.write("\"/>\r\n");
      out.write("                                    <button type=\"button\" onclick=\"tj()\" class=\"btn btn-primary mt-4\">提交</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("      \r\n");
      out.write("        <!-- Modal Custom Settings-->\r\n");
      out.write("       <div class=\"modal fade right\" id=\"Settingmodal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog  modal-sm\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <h5 class=\"modal-title\">Custom Settings</h5>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body custom_setting\">\r\n");
      out.write("                        <!-- Settings: Color -->\r\n");
      out.write("                        <div class=\"setting-theme pb-3\">\r\n");
      out.write("                            <h6 class=\"card-title mb-2 fs-6 d-flex align-items-center\"><i class=\"icofont-color-bucket fs-4 me-2 text-primary\"></i>Template Color Settings</h6>\r\n");
      out.write("                            <ul class=\"list-unstyled row row-cols-3 g-2 choose-skin mb-2 mt-2\">\r\n");
      out.write("                                <li data-theme=\"indigo\"><div class=\"indigo\"></div></li>\r\n");
      out.write("                                <li data-theme=\"tradewind\" class=\"active\"><div class=\"tradewind\"></div></li>\r\n");
      out.write("                                <li data-theme=\"monalisa\"><div class=\"monalisa\"></div></li>\r\n");
      out.write("                                <li data-theme=\"blue\"><div class=\"blue\"></div></li>\r\n");
      out.write("                                <li data-theme=\"cyan\"><div class=\"cyan\"></div></li>\r\n");
      out.write("                                <li data-theme=\"green\"><div class=\"green\"></div></li>\r\n");
      out.write("                                <li data-theme=\"orange\"><div class=\"orange\"></div></li>\r\n");
      out.write("                                <li data-theme=\"blush\"><div class=\"blush\"></div></li>\r\n");
      out.write("                                <li data-theme=\"red\"><div class=\"red\"></div></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sidebar-gradient py-3\">\r\n");
      out.write("                            <h6 class=\"card-title mb-2 fs-6 d-flex align-items-center\"><i class=\"icofont-paint fs-4 me-2 text-primary\"></i>Sidebar Gradient</h6>\r\n");
      out.write("                            <div class=\"form-check form-switch gradient-switch pt-2 mb-2\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" id=\"CheckGradient\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"CheckGradient\">Enable Gradient! ( Sidebar )</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Settings: Template dynamics -->\r\n");
      out.write("                        <div class=\"dynamic-block py-3\">\r\n");
      out.write("                            <ul class=\"list-unstyled choose-skin mb-2 mt-1\">\r\n");
      out.write("                                <li data-theme=\"dynamic\"><div class=\"dynamic\"><i class=\"icofont-paint me-2\"></i> Click to Dyanmic Setting</div></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"dt-setting\">\r\n");
      out.write("                                <ul class=\"list-group list-unstyled mt-1\">\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label>Primary Color</label>\r\n");
      out.write("                                        <button id=\"primaryColorPicker\" class=\"btn bg-primary avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label>Secondary Color</label>\r\n");
      out.write("                                        <button id=\"secondaryColorPicker\" class=\"btn bg-secondary avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 1</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker1\" class=\"btn chart-color1 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 2</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker2\" class=\"btn chart-color2 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 3</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker3\" class=\"btn chart-color3 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 4</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker4\" class=\"btn chart-color4 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 5</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker5\" class=\"btn chart-color5 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Settings: Font -->\r\n");
      out.write("                        <div class=\"setting-font py-3\">\r\n");
      out.write("                            <h6 class=\"card-title mb-2 fs-6 d-flex align-items-center\"><i class=\"icofont-font fs-4 me-2 text-primary\"></i> Font Settings</h6>\r\n");
      out.write("                            <ul class=\"list-group font_setting mt-1\">\r\n");
      out.write("                                <li class=\"list-group-item py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"font\" id=\"font-poppins\" value=\"font-poppins\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"font-poppins\">\r\n");
      out.write("                                            Poppins Google Font\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"font\" id=\"font-opensans\" value=\"font-opensans\" checked=\"\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"font-opensans\">\r\n");
      out.write("                                            Open Sans Google Font\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"font\" id=\"font-montserrat\" value=\"font-montserrat\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"font-montserrat\">\r\n");
      out.write("                                            Montserrat Google Font\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"font\" id=\"font-mukta\" value=\"font-mukta\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"font-mukta\">\r\n");
      out.write("                                            Mukta Google Font\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Settings: Light/dark -->\r\n");
      out.write("                        <div class=\"setting-mode py-3\">\r\n");
      out.write("                            <h6 class=\"card-title mb-2 fs-6 d-flex align-items-center\"><i class=\"icofont-layout fs-4 me-2 text-primary\"></i>Contrast Layout</h6>\r\n");
      out.write("                            <ul class=\"list-group list-unstyled mb-0 mt-1\">\r\n");
      out.write("                                <li class=\"list-group-item d-flex align-items-center py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check form-switch theme-switch mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"checkbox\" id=\"theme-switch\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"theme-switch\">Enable Dark Mode!</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item d-flex align-items-center py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check form-switch theme-high-contrast mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"checkbox\" id=\"theme-high-contrast\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"theme-high-contrast\">Enable High Contrast</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item d-flex align-items-center py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check form-switch theme-rtl mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"checkbox\" id=\"theme-rtl\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"theme-rtl\">Enable RTL Mode!</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-footer justify-content-start\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-white border lift\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary lift\">Save Changes</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>       \r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Core Js -->\r\n");
      out.write("<script src=\"static/js/libscripts.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Page Js -->\r\n");
      out.write("<script src=\"static/js/template.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
