/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-11 01:19:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxnu.entity.Feedback;
import java.util.List;
import com.gxnu.service.imp.FeedbackService;
import com.gxnu.service.IFeedbackService;
import com.gxnu.util.Data;

public final class Feedback_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxnu.entity.Feedback");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gxnu.util.Data");
    _jspx_imports_classes.add("com.gxnu.service.IFeedbackService");
    _jspx_imports_classes.add("com.gxnu.service.imp.FeedbackService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

	int pageSize=10;			//每一页 上显示信息的最大条数
	int firstPage=1;		//首页的页码
	int previousPage=1;		//上一页的页码
	int nextPage=1;			//下一页的页码
	int lastPage=1;			//最后一页的页码
	int currentPage=1;		//当前的页码
	
	//获取请求参数P，该值为要显示的页码
	String cp = request.getParameter("P");
	if(cp!=null){
		currentPage = Integer.parseInt(cp);
	}

   //调用业务方法，检索所有菜单信息
   IFeedbackService feedbackService = new FeedbackService();
   List<Feedback> feedbacks = feedbackService.find();
   int total = feedbacks.size(); //最记录条数
   //分页
   feedbacks = feedbackService.find(currentPage,pageSize);
   
   //最后一页的页码
   if(total%pageSize==0){
	   lastPage = total/pageSize;
   }else{
	   lastPage = total/pageSize + 1;
   }
   
	//得到上一页的页号
   previousPage=currentPage-1;
   if(previousPage<=firstPage){
	previousPage=firstPage;
   }
	
   //得到下一页的页号
   nextPage=currentPage+1;
   if(nextPage>=lastPage){
	 nextPage=lastPage;
   }
   

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>:: 后台管理::  留言反馈 </title>\r\n");
      out.write("    <!-- plugin css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/responsive.dataTables.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/dataTables.bootstrap5.min.css\">\r\n");
      out.write("    <!-- project css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/ihealth.style.min.css\">\r\n");
      out.write("    <script>\r\n");
      out.write("   function xxx(n){\r\n");
      out.write("\t   //重新跳转到menu.jsp，即“刷新tab.jsp”,且把要显示的号码以请求参数的方法进行传递，如 P=4\r\n");
      out.write("\t   window.location.href=\"");
      out.print(Data.URL+"/Manage/Feedback.jsp?P=");
      out.write("\"+n;\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"ihealth-layout\" class=\"theme-tradewind\">\r\n");
      out.write("   <div class=\"main px-lg-4 px-md-4\">\r\n");
      out.write("        <!-- Body: Body -->\r\n");
      out.write("        <div class=\"body d-flex py-3\">\r\n");
      out.write("            <div class=\"container-xxl\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"border-0 mb-4\">\r\n");
      out.write("                        <div class=\"card-header py-3 no-bg bg-transparent d-flex align-items-center px-0 justify-content-between border-bottom flex-wrap\">\r\n");
      out.write("                            <h3 class=\"fw-bold mb-0\">留言反馈管理</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> \r\n");
      out.write("                \r\n");
      out.write("                <!-- 页码显示、搜索框 -->\r\n");
      out.write("               \r\n");
      out.write("                  <table border=\"0\" style=\"width:85%\"><tr>\r\n");
      out.write("                              <td>  <table border=\"0\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                               <td style=\"align:right\"> 每页</td>\r\n");
      out.write("                               <td style=\"width:40%\">\r\n");
      out.write("                               <select name=\"editable_length\" aria-controls=\"editable\" class=\"form-control input-sm\"  style=\"width:100px;margin: 0 auto\">\r\n");
      out.write("                             \t<option value=\"10\"  >10</option>\r\n");
      out.write("                             \t<option value=\"25\">25</option>\r\n");
      out.write("                             \t<option value=\"50\">50</option>\r\n");
      out.write("                             \t</select></td>  <td style=\"margin:60%;\">条记录</br></td>\r\n");
      out.write("                               </tr></table></td>\r\n");
      out.write("                               \r\n");
      out.write("                                <!-- 搜索框的设置 -->\r\n");
      out.write("                               <td> <table border=\"0\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                <td id=\"editable_filter\" class=\"dataTables_filter\"> 搜索：</td>\r\n");
      out.write("                                <td><input type=\"search\" class=\"form-control form-control-sm\" placeholder=\"\" aria-controls=\"patient-table\"></td>\r\n");
      out.write("                                </tr></table></td>\r\n");
      out.write("                                \r\n");
      out.write("                                </tr></td></table>\r\n");
      out.write("                                </br>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Row end  -->\r\n");
      out.write("                <div class=\"row mb-3\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <table id=\"patient-table\" class=\"table table-hover align-middle mb-0\" style=\"width: 100%;\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th>序号</th>\r\n");
      out.write("                                        <th>时间</th>\r\n");
      out.write("                                        <th>内容</th>        \r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                      ");

			            //循环遍历集合，每循环一次，生成一行html<tr></tr>，在每一个单元格中 <td></td>,把静态数据改成数据库表中的记录
			            for(Feedback feedback : feedbacks ) {
			          
      out.write("\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>");
      out.print(feedbacks.indexOf(feedback)+1);
      out.write("</td>\r\n");
      out.write("                                        <td><span>");
      out.print(feedback.getTime() );
      out.write("</span></td>\r\n");
      out.write("                                        <td>");
      out.print(feedback.getContent());
      out.write("</td>\r\n");
      out.write("                                    </tr> ");
} 
      out.write("\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("      <table style=\"width: 100%;\"><tr>\r\n");
      out.write("      <td class=\"dataTables_info\" id=\"patient-table_info\" role=\"status\" aria-live=\"polite\">显示1至10个结果，共 ");
      out.print(total );
      out.write("条记录</td>\r\n");
      out.write("     \r\n");
      out.write("      <td><ul class=\"pagination\">\r\n");
      out.write("      <li class=\"paginate_button page-item previous disabled\" id=\"patient-table_previous\">\r\n");
      out.write("       <input type=\"button\" value=\"上一页\"  onclick=\"xxx(");
      out.print(previousPage);
      out.write(")\" aria-controls=\"patient-table\" data-dt-idx=\"0\" tabindex=\"0\"/></li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("      <li class=\"paginate_button page-item active\">\r\n");
      out.write("      <a href=\"#\" aria-controls=\"patient-table\" data-dt-idx=\"1\" tabindex=\"0\" >");
      out.print(currentPage );
      out.write('/');
      out.print(lastPage );
      out.write("页 </a></li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("      <li class=\"paginate_button page-item next disabled\" id=\"patient-table_next\">\r\n");
      out.write("      <input type=\"button\" value=\"下一页\"  onclick=\"xxx(");
      out.print(nextPage);
      out.write(")\"/></li>\r\n");
      out.write("       </ul></td>\r\n");
      out.write("       \r\n");
      out.write("     <td>  \r\n");
      out.write("     <button style=\"display:block;margin:70 auto\" type=\"\" class=\"btn btn-primary mt-4\" onclick=\"javascript:window.location.href='");
      out.print(Data.URL);
      out.write("/Manage/index.html'\"/>返回</button>\r\n");
      out.write("     </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     </table>\r\n");
      out.write("       \r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("        <!-- Modal Custom Settings-->\r\n");
      out.write("       <div class=\"modal fade right\" id=\"Settingmodal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog  modal-sm\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <h5 class=\"modal-title\">Custom Settings</h5>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body custom_setting\">\r\n");
      out.write("                        <!-- Settings: Color -->\r\n");
      out.write("                        <div class=\"setting-theme pb-3\">\r\n");
      out.write("                            <h6 class=\"card-title mb-2 fs-6 d-flex align-items-center\"><i class=\"icofont-color-bucket fs-4 me-2 text-primary\"></i>Template Color Settings</h6>\r\n");
      out.write("                            <ul class=\"list-unstyled row row-cols-3 g-2 choose-skin mb-2 mt-2\">\r\n");
      out.write("                                <li data-theme=\"indigo\"><div class=\"indigo\"></div></li>\r\n");
      out.write("                                <li data-theme=\"tradewind\" class=\"active\"><div class=\"tradewind\"></div></li>\r\n");
      out.write("                                <li data-theme=\"monalisa\"><div class=\"monalisa\"></div></li>\r\n");
      out.write("                                <li data-theme=\"blue\"><div class=\"blue\"></div></li>\r\n");
      out.write("                                <li data-theme=\"cyan\"><div class=\"cyan\"></div></li>\r\n");
      out.write("                                <li data-theme=\"green\"><div class=\"green\"></div></li>\r\n");
      out.write("                                <li data-theme=\"orange\"><div class=\"orange\"></div></li>\r\n");
      out.write("                                <li data-theme=\"blush\"><div class=\"blush\"></div></li>\r\n");
      out.write("                                <li data-theme=\"red\"><div class=\"red\"></div></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sidebar-gradient py-3\">\r\n");
      out.write("                            <h6 class=\"card-title mb-2 fs-6 d-flex align-items-center\"><i class=\"icofont-paint fs-4 me-2 text-primary\"></i>Sidebar Gradient</h6>\r\n");
      out.write("                            <div class=\"form-check form-switch gradient-switch pt-2 mb-2\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" id=\"CheckGradient\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"CheckGradient\">Enable Gradient! ( Sidebar )</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Settings: Template dynamics -->\r\n");
      out.write("                        <div class=\"dynamic-block py-3\">\r\n");
      out.write("                            <ul class=\"list-unstyled choose-skin mb-2 mt-1\">\r\n");
      out.write("                                <li data-theme=\"dynamic\"><div class=\"dynamic\"><i class=\"icofont-paint me-2\"></i> Click to Dyanmic Setting</div></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"dt-setting\">\r\n");
      out.write("                                <ul class=\"list-group list-unstyled mt-1\">\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label>Primary Color</label>\r\n");
      out.write("                                        <button id=\"primaryColorPicker\" class=\"btn bg-primary avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label>Secondary Color</label>\r\n");
      out.write("                                        <button id=\"secondaryColorPicker\" class=\"btn bg-secondary avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 1</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker1\" class=\"btn chart-color1 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 2</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker2\" class=\"btn chart-color2 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 3</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker3\" class=\"btn chart-color3 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 4</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker4\" class=\"btn chart-color4 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center py-1 px-2\">\r\n");
      out.write("                                        <label class=\"text-muted\">Chart Color 5</label>\r\n");
      out.write("                                        <button id=\"chartColorPicker5\" class=\"btn chart-color5 avatar xs border-0 rounded-0\"></button>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Settings: Font -->\r\n");
      out.write("                        <div class=\"setting-font py-3\">\r\n");
      out.write("                            <h6 class=\"card-title mb-2 fs-6 d-flex align-items-center\"><i class=\"icofont-font fs-4 me-2 text-primary\"></i> Font Settings</h6>\r\n");
      out.write("                            <ul class=\"list-group font_setting mt-1\">\r\n");
      out.write("                                <li class=\"list-group-item py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"font\" id=\"font-poppins\" value=\"font-poppins\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"font-poppins\">\r\n");
      out.write("                                            Poppins Google Font\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"font\" id=\"font-opensans\" value=\"font-opensans\" checked=\"\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"font-opensans\">\r\n");
      out.write("                                            Open Sans Google Font\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"font\" id=\"font-montserrat\" value=\"font-montserrat\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"font-montserrat\">\r\n");
      out.write("                                            Montserrat Google Font\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"font\" id=\"font-mukta\" value=\"font-mukta\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"font-mukta\">\r\n");
      out.write("                                            Mukta Google Font\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Settings: Light/dark -->\r\n");
      out.write("                        <div class=\"setting-mode py-3\">\r\n");
      out.write("                            <h6 class=\"card-title mb-2 fs-6 d-flex align-items-center\"><i class=\"icofont-layout fs-4 me-2 text-primary\"></i>Contrast Layout</h6>\r\n");
      out.write("                            <ul class=\"list-group list-unstyled mb-0 mt-1\">\r\n");
      out.write("                                <li class=\"list-group-item d-flex align-items-center py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check form-switch theme-switch mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"checkbox\" id=\"theme-switch\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"theme-switch\">Enable Dark Mode!</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item d-flex align-items-center py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check form-switch theme-high-contrast mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"checkbox\" id=\"theme-high-contrast\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"theme-high-contrast\">Enable High Contrast</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-group-item d-flex align-items-center py-1 px-2\">\r\n");
      out.write("                                    <div class=\"form-check form-switch theme-rtl mb-0\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"checkbox\" id=\"theme-rtl\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"theme-rtl\">Enable RTL Mode!</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-footer justify-content-start\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-white border lift\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary lift\">Save Changes</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("     </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--Jquery核心Js-->\r\n");
      out.write("<script src=\"static/js/libscripts.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 插件Js-->\r\n");
      out.write("<script src=\"static/js/dataTables.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery页面Js -->\r\n");
      out.write("<script src=\"static/js/template.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
