/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-11 02:33:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxnu.entity.Operator;
import com.gxnu.util.Data;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxnu.util.Data");
    _jspx_imports_classes.add("com.gxnu.entity.Operator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    Object obj = session.getAttribute(Data.OPERATOR);
    Operator operator = new Operator();
    if(obj!=null){
    	operator=(Operator)obj; 
    }
   // System.out.println(operator+"opopopopoopopop");  
    
      out.write("      \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>后台管理 </title>\r\n");
      out.write("    <!-- plugin css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/responsive.dataTables.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/dataTables.bootstrap5.min.css\">\r\n");
      out.write("    <!-- project css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/ihealth.style.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"ihealth-layout\" class=\"theme-tradewind\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- sidebar -->\r\n");
      out.write("    <div class=\"sidebar px-4 py-4 py-md-5 me-0\">\r\n");
      out.write("        <div class=\"d-flex flex-column h-100\">\r\n");
      out.write("            <a href=\"\" class=\"mb-0 brand-icon\">\r\n");
      out.write("                <span class=\"logo-icon\">\r\n");
      out.write("                    <i class=\"icofont-heart-beat fs-2\"></i>\r\n");
      out.write("                </span>\r\n");
      out.write("                <span class=\"logo-text\">菜单</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <!-- Menu: main ul -->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"menu-list flex-grow-1 mt-3\">\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                <!-- data-bs-toggle=\"collapse\" data-bs-target=\"#dashboard\" -->\r\n");
      out.write("                <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/Menu.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                <i class=\"icofont-ui-home fs-5\"></i><span>菜单管理</span>  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                <!-- data-bs-toggle=\"collapse\" data-bs-target=\"#authorization\" -->\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/Authorization1.jsp\" target=\"IFrameBox\" >\r\n");
      out.write("                        <i class=\"icofont-stamp\"></i> <span>权限管理</span> </a>\r\n");
      out.write("                    <!-- 权限 子菜单 -->\r\n");
      out.write("                   <!--  <ul class=\"sub-menu collapse\" id=\"authorization\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"Authorization1.html\" target=\"IFrameBox\">1</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\"> 2</a></li>\r\n");
      out.write("                    </ul> -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/Patient.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-crutch\"></i> <span>患者信息管理</span> </a>\r\n");
      out.write("                    <!--患者 子菜单 -->\r\n");
      out.write("                    <!-- <ul class=\"sub-menu collapse\" id=\"menu-Patient\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">1</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\"> 2</a></li>\r\n");
      out.write("                    </ul> -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\" data-bs-toggle=\"collapse\" data-bs-target=\"#case\" href=\"#\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-prescription\"></i> <span>病例信息管理</span> <span\r\n");
      out.write("                            class=\"arrow icofont-rounded-down ms-auto text-end fs-5\"></span></a>\r\n");
      out.write("                    <!--病例 子菜单 -->\r\n");
      out.write("                    <ul class=\"sub-menu collapse\" id=\"case\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"");
      out.print(Data.URL );
      out.write("/Manage/Case.jsp\" target=\"IFrameBox\">病例信息查看</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"");
      out.print(Data.URL );
      out.write("/Manage/Registration.jsp\" target=\"IFrameBox\"> 预约挂号统计</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                <!-- data-bs-toggle=\"collapse\" data-bs-target=\"#dashboard\" -->\r\n");
      out.write("                <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/Image.jsp\" target=\"IFrameBox\">\r\n");
      out.write("\t                <i class=\"icofont-ui-home fs-5\"></i><span>图片信息管理</span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/Doctor.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-doctor\"></i> <span>医生信息管理</span> <!-- <span\r\n");
      out.write("                            class=\"arrow icofont-rounded-down ms-auto text-end fs-5\"></span> --></a>\r\n");
      out.write("                    <!--医生 子菜单 -->\r\n");
      out.write("                   ");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/ScheduleStart.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-ui-calendar\"></i> <span>排班信息管理</span> </span></a>\r\n");
      out.write("                    <!--排班 子菜单 -->\r\n");
      out.write("                    <!-- <ul class=\"sub-menu collapse \" id=\"schedule\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">1</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\"> 2</a></li>\r\n");
      out.write("                    </ul> -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("               <!--  data-bs-toggle=\"collapse\" data-bs-target=\"#drug\" -->\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/Drug.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-pills\"></i> <span>药品信息管理</span> </a>\r\n");
      out.write("                    <!--药品 子菜单 -->\r\n");
      out.write("                    <!-- <ul class=\"sub-menu collapse \" id=\"drug\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">药品入库</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">入库明细</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">药品出库</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">出库明细</a></li>\r\n");
      out.write("                    </ul> -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/Typical_case.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-patient-file\"></i> <span>经典案例信息管理</span> </a>\r\n");
      out.write("                    <!--经典案例 子菜单 -->\r\n");
      out.write("                    <!-- <ul class=\"sub-menu collapse \" id=\"typicalcase\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">1</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\"> 2</a></li>\r\n");
      out.write("                    </ul> -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\" data-bs-toggle=\"collapse\" data-bs-target=\"#unit\" href=\"#\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-ui-home fs-5\"></i> <span>科室信息管理</span> <span\r\n");
      out.write("                            class=\"arrow icofont-rounded-down ms-auto text-end fs-5\"></span></a>\r\n");
      out.write("                    <!--科室 子菜单 -->\r\n");
      out.write("                    <ul class=\"sub-menu collapse \" id=\"unit\">\r\n");
      out.write("                    \t<li><a class=\"ms-link\" href=\"");
      out.print(Data.URL );
      out.write("/Manage/Unit.jsp\" target=\"IFrameBox\">科室管理</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"");
      out.print(Data.URL );
      out.write("/Manage/Meesure.jsp\" target=\"IFrameBox\">统计</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\" href=\"");
      out.print(Data.URL );
      out.write("/Manage/Article.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-mathematical\"></i> <span>科普文章管理</span> </a>\r\n");
      out.write("                    <!--科普文章 子菜单 -->\r\n");
      out.write("                    <!-- <ul class=\"sub-menu collapse \" id=\"article\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">1</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\"> 2</a></li>\r\n");
      out.write("                    </ul> -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/Recipe.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-patient-file\"></i> <span>处方信息管理</span><!--  <span\r\n");
      out.write("                            class=\"arrow icofont-rounded-down ms-auto text-end fs-5\"></span> --></a>\r\n");
      out.write("                    <!--处方信息 子菜单 -->\r\n");
      out.write("                    <!-- <ul class=\"sub-menu collapse \" id=\"recipe\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">1</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\"> 2</a></li>\r\n");
      out.write("                    </ul> -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL );
      out.write("/Manage/About.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-hospital\"></i> <span>关于医院信息管理</span> <span></span></a>\r\n");
      out.write("                    <!--关于医院 子菜单 -->\r\n");
      out.write("                    <!-- <ul class=\"sub-menu collapse\" id=\"about\">\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\">1</a></li>\r\n");
      out.write("                        <li><a class=\"ms-link\" href=\"\" target=\"IFrameBox\"> 2</a></li>\r\n");
      out.write("                    </ul> -->\r\n");
      out.write("                   </li>\r\n");
      out.write("                  <li class=\"collapsed\">\r\n");
      out.write("                           <a  class=\"m-link\"  href=\"");
      out.print(Data.URL);
      out.write("/Manage/reserve_case.jsp\" target=\"IFrameBox\"  >    \r\n");
      out.write("                        <i class=\"icofont-hospital\"></i> <span>可预约情况查看</span></a>                        \r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"collapsed\">\r\n");
      out.write("                    <a class=\"m-link\"  href=\"");
      out.print(Data.URL);
      out.write("/Manage/Feedback.jsp\" target=\"IFrameBox\">\r\n");
      out.write("                        <i class=\"icofont-mathematical\"></i> <span>留言反馈</span> <span ></span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("           \r\n");
      out.write("            <!-- Menu: menu collepce btn -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- main body area -->\r\n");
      out.write("    <div class=\"main px-lg-4 px-md-4\">\r\n");
      out.write("        <!-- Body: Header -->\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <nav class=\"navbar py-4\">\r\n");
      out.write("                <div class=\"container-xxl\">\r\n");
      out.write("                    <!-- header rightbar icon -->\r\n");
      out.write("                    <div class=\"h-right d-flex align-items-center mr-5 mr-lg-0 order-1\">\r\n");
      out.write("                        <div class=\"dropdown user-profile ml-2 ml-sm-3 d-flex align-items-center zindex-popover\">\r\n");
      out.write("                            <div class=\"u-info me-2\">\r\n");
      out.write("                                <p class=\"mb-0 text-end line-height-sm \"><span class=\"font-weight-bold\">");
      out.print(operator.getRole().getName() );
      out.write("</span></p>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle pulse p-0\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" data-bs-display=\"static\">\r\n");
      out.write("                                <img class=\"avatar lg rounded-circle img-thumbnail\" src=\"static/picture/profile_av.png\" alt=\"profile\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"dropdown-menu rounded-lg shadow border-0 dropdown-animation dropdown-menu-end p-0 m-0\">\r\n");
      out.write("                                <div class=\"card border-0 w280\">\r\n");
      out.write("                                    <div class=\"card-body pb-0\">\r\n");
      out.write("                                        <div class=\"d-flex py-1\">\r\n");
      out.write("                                            <img class=\"avatar rounded-circle\" src=\"static/picture/profile_av.png\" alt=\"profile\">\r\n");
      out.write("                                            <div class=\"flex-fill ms-3\">\r\n");
      out.write("                                                <p class=\"mb-0\"><span class=\"font-weight-bold\">John\tQuinn</span></p>\r\n");
      out.write("                                                <small class=\"\">");
      out.print(operator.getEmail() );
      out.write("</small>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div><hr class=\"dropdown-divider border-dark\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"list-group m-2 \">\r\n");
      out.write("                                        <a href=\"");
      out.print(Data.URL);
      out.write("/Manage/operator1.jsp\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-ui-video-chat fs-5 me-3\"></i>个人信息修改</a>\r\n");
      out.write("                                        <a href=\"");
      out.print(Data.URL);
      out.write("/Manage/Login.jsp\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-logout fs-6 me-3\"></i>退出</a>\r\n");
      out.write("                                        <div><hr class=\"dropdown-divider border-dark\"></div>\r\n");
      out.write("                                        <a href=\"javascript:;\" class=\"list-group-item list-group-item-action border-0 \"><i class=\"icofont-contact-add fs-5 me-3\"></i>添加管理员</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"setting ms-2\">\r\n");
      out.write("                            <a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#Settingmodal\"><i class=\"icofont-gear-alt fs-5\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- main menu Search-->\r\n");
      out.write("                    <div class=\"order-0 col-lg-4 col-md-4 col-sm-12 col-12 mb-3 mb-md-0 \">\r\n");
      out.write("                        <div class=\"input-group flex-nowrap input-group-lg\">\r\n");
      out.write("                            <input type=\"search\" class=\"form-control\" placeholder=\"Search\" aria-label=\"search\" aria-describedby=\"addon-wrapping\">\r\n");
      out.write("                            <button type=\"button\" class=\"input-group-text\" id=\"addon-wrapping\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>  \r\n");
      out.write("        <!--中间内容显示-->   \r\n");
      out.write("        <div style=\"padding: 0px; width: 100%; height: 800px;\">\r\n");
      out.write("            <iframe name=\"IFrameBox\" src=\"");
      out.print(Data.URL );
      out.write("/Manage/Menu.jsp\" frameborder=\"1\"\r\n");
      out.write("                width=\"100%\" height=\"100%\" scrolling=\"No\" noresize=\"noresize\"></iframe>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Core Js -->\r\n");
      out.write("<script src=\"static/js/libscripts.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin Js -->\r\n");
      out.write("<script src=\"static/js/apexcharts.bundle.js\"></script>\r\n");
      out.write("<script src=\"static/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"static/js/owl.carousel.js\"></script>\r\n");
      out.write("<script src=\"static/js/dataTables.bundle.js\"></script>      \r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Page Js -->\r\n");
      out.write("<script src=\"static/js/template.js\"></script>\r\n");
      out.write("<script src=\"static/js/index.js\"></script>\r\n");
      out.write(" <script>\r\n");
      out.write("      $('#myDataTable')\r\n");
      out.write("      .addClass( 'nowrap' )\r\n");
      out.write("      .dataTable( {\r\n");
      out.write("          responsive: true,\r\n");
      out.write("          columnDefs: [\r\n");
      out.write("              { targets: [-1, -3], className: 'dt-body-right' }\r\n");
      out.write("          ]\r\n");
      out.write("      });\r\n");
      out.write(" </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
