/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-10 11:05:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxnu.entity.Measure;
import com.gxnu.service.imp.MeasureService;
import com.gxnu.service.IMeasureService;
import com.gxnu.entity.Inventory;
import com.gxnu.service.imp.InventoryService;
import com.gxnu.service.IInventoryService;
import com.gxnu.util.Data;
import com.gxnu.entity.InDetail;
import java.util.List;
import com.gxnu.service.imp.InDetailService;
import com.gxnu.service.IInDetailService;
import com.gxnu.service.IInStoreService;

public final class InStore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxnu.service.IInStoreService");
    _jspx_imports_classes.add("com.gxnu.entity.InDetail");
    _jspx_imports_classes.add("com.gxnu.util.Data");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gxnu.service.IInDetailService");
    _jspx_imports_classes.add("com.gxnu.service.IInventoryService");
    _jspx_imports_classes.add("com.gxnu.entity.Measure");
    _jspx_imports_classes.add("com.gxnu.service.imp.InDetailService");
    _jspx_imports_classes.add("com.gxnu.entity.Inventory");
    _jspx_imports_classes.add("com.gxnu.service.IMeasureService");
    _jspx_imports_classes.add("com.gxnu.service.imp.MeasureService");
    _jspx_imports_classes.add("com.gxnu.service.imp.InventoryService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>:: 入库明细</title>\r\n");
      out.write("    <!-- Summernote css -->\r\n");
      out.write("    <link href=\"static/css/summernote-bs4.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <!-- plugin css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/responsive.dataTables.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/dataTables.bootstrap5.min.css\">\r\n");
      out.write("    <!-- project css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/ihealth.style.min.css\">\r\n");
      out.write("    <!-- Bootstrap Css -->\r\n");
      out.write("    <link href=\"static/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <!-- Icons Css -->\r\n");
      out.write("    <link href=\"static/css/icons.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <!-- App Css-->\r\n");
      out.write("    <link href=\"static/css/app.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"ihealth-layout\" class=\"theme-tradewind\">\r\n");
      out.write("\r\n");
      out.write("        <!-- sidebar -->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <!-- main body area -->\r\n");
      out.write("        <div class=\"main px-lg-4 px-md-4\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Body: Header -->\r\n");
      out.write("            \r\n");
      out.write("            <!-- Body: Body -->\r\n");
      out.write("            <div class=\"body d-flex py-lg-3 py-md-2\">\r\n");
      out.write("                <div class=\"container-xxl\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"border-0 mb-4\">\r\n");
      out.write("                            <div\r\n");
      out.write("                                class=\"card-header py-3 no-bg bg-transparent d-flex align-items-center px-0 justify-content-between border-bottom flex-wrap\">\r\n");
      out.write("                                <h3 class=\"fw-bold mb-0\">入库记录</h3>\r\n");
      out.write("                                <div class=\"col-auto d-flex w-sm-100\">\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-primary btn-set-task w-sm-100\"\r\n");
      out.write("                                        data-bs-toggle=\"modal\" data-bs-target=\"#depadd\"><i\r\n");
      out.write("                                            class=\"icofont-plus-circle me-2 fs-6\"></i>添加</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> <!-- Row end  -->\r\n");
      out.write("                    <div class=\"row clearfix g-3\">\r\n");
      out.write("                        <div class=\"col-sm-12\">\r\n");
      out.write("                            <div class=\"card mb-3\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <table id=\"myProjectTable\" class=\"table table-hover align-middle mb-0\"\r\n");
      out.write("                                        style=\"width:100%\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"col\">id</th>\r\n");
      out.write("                                                <th scope=\"col\">药品名称</th>\r\n");
      out.write("                                                <th scope=\"col\">进货价格</th>\r\n");
      out.write("                                                <th scope=\"col\">数量</th>\r\n");
      out.write("                                                <th scope=\"col\">单位</th>\r\n");
      out.write("                                                <th scope=\"col\">基本操作</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                           ");
 
                                           //获取会话中传过来的入库InStoreId，循环遍历，若入库明细的入库id等于InStoreId,则输出
                                             Object instoreId = session.getAttribute("InStoreId");
                                             int inStoreId = 0;
                                             if(instoreId!=null){inStoreId = Integer.parseInt(String.valueOf(instoreId));}
                                             IInDetailService ids = new InDetailService();
                                             List<InDetail> inDetails = ids.findAll();
                                             int i = 1;
                                             for(InDetail inDetail : inDetails){
                                            	 if(inDetail.getInStore().getId()==inStoreId){
                                           
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <span class=\"fw-bold\">");
      out.print(i++ );
      out.write("</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <!-- 药品名称 -->\r\n");
      out.write("                                                    <span class=\"fw-bold ms-1\">");
      out.print(inDetail.getInventory().getDrugInfo().getName());
      out.write("</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <!-- 进货价格 -->\r\n");
      out.write("                                                   <span>");
      out.print(inDetail.getPrice());
      out.write("</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <!-- 数量 -->\r\n");
      out.write("                                                    <span>");
      out.print(inDetail.getNum());
      out.write("</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                \t<!-- 单位-->\r\n");
      out.write("                                                    <span>");
      out.print(inDetail.getInventory().getMeasur().getName());
      out.write("</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div class=\"btn-group\" role=\"group\"\r\n");
      out.write("                                                        aria-label=\"Basic outlined example\">\r\n");
      out.write("                                                        \r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-secondary\"\r\n");
      out.write("                                                            data-bs-toggle=\"modal\" data-bs-target=\"#depedit\" onclick=\"edit(this,");
      out.print(inDetail.getId());
      out.write(',');
      out.print(inDetail.getInventory().getId());
      out.write(")\"><i\r\n");
      out.write("                                                                class=\"icofont-edit text-success\"></i></button>\r\n");
      out.write("                                                                \r\n");
      out.write("                                                        <button type=\"button\"\r\n");
      out.write("                                                            onclick=\"window.location.href='");
      out.print(Data.URL);
      out.write("/indetail?OP=delete&ID=");
      out.print(inDetail.getId());
      out.write("'\"><i\r\n");
      out.write("                                                                class=\"icofont-ui-delete text-danger\"></i></button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            ");
}} 
      out.write("\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div><!-- Row End -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"margin-left:90%\" class=\"col-auto d-flex w-sm-100\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary btn-set-task w-sm-100\"\r\n");
      out.write("                        data-bs-toggle=\"modal\" onclick=\"window.location.href='");
      out.print(Data.URL);
      out.write("/Manage/Drug.jsp'\">完成入库</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Modal Custom Settings-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 添加入库明细-->\r\n");
      out.write("            <div class=\"modal fade\" id=\"depadd\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-centered modal-md modal-dialog-scrollable\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h5 class=\"modal-title  fw-bold\" id=\"depaddLabel\">添加入库明细</h5>\r\n");
      out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"deadline-form\">\r\n");
      out.write("                                <form action=\"");
      out.print(Data.URL);
      out.write("/indetail?OP=add\" method=\"post\">\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"depone\" class=\"form-label\">药品名称</label>\r\n");
      out.write("                                        <select name=\"INVENTORY\">\r\n");
      out.write("\t\t\t\t\t\t\t\t            <option value=\"1\" selected=\"selected\">--请选择药品--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t            ");

								            IInventoryService irs = new InventoryService();
								            List<Inventory> inventories = irs.find();
								            for(Inventory inventory : inventories){          
								            
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t            <option value=\"");
      out.print(inventory.getId());
      out.write("\">--");
      out.print(inventory.getDrugInfo().getName());
      out.write("--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t            ");
}
      out.write("           \r\n");
      out.write("\t\t\t\t\t\t\t\t        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"deptwo\" class=\"form-label\">进货价格</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"deptwo\" name=\"PRICE\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"depthree\" class=\"form-label\">数量</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"depthree\" name=\"NUM\">\r\n");
      out.write("                                        <!-- <input type=\"hidden\" class=\"form-control\" name=\"INSTOREID\" value=\"");
      out.print(inStoreId);
      out.write("\">  -->\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"summernote\"></div>\r\n");
      out.write("                                    <!-- end row -->\r\n");
      out.write("                                    <!-- end row -->\r\n");
      out.write("                                    <!-- end container-fluid -->\r\n");
      out.write("                                    <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">取消</button>\r\n");
      out.write("\t\t\t                            <button type=\"submit\" class=\"btn btn-primary\">添加</button>\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 编辑入库明细-->\r\n");
      out.write("            <div class=\"modal fade\" id=\"depedit\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-centered modal-md modal-dialog-scrollable\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h5 class=\"modal-title  fw-bold\" id=\"depeditLabel\"> 编辑药品</h5>\r\n");
      out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"deadline-form\">\r\n");
      out.write("                                <form action=\"");
      out.print(Data.URL);
      out.write("/indetail?OP=update\" method=\"post\">\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <input type=\"hidden\" class=\"form-control\" id=\"updateInventory\" name=\"INVENTORY\">\r\n");
      out.write("                                        <input type=\"hidden\" class=\"form-control\" id=\"updateId\" name=\"ID\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"depone\" class=\"form-label\">进货价格</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"updatePrice\" name=\"PRICE\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"deptwo\" class=\"form-label\">数量</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"updateNum\" name=\"NUM\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">取消</button>\r\n");
      out.write("\t\t\t                            <button type=\"submit\" class=\"btn btn-primary\">保存</button>\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Core Js -->\r\n");
      out.write("    <script src=\"static/js/libscripts.bundle.js\"></script>\r\n");
      out.write("    <!-- JAVASCRIPT -->\r\n");
      out.write("    <script src=\"static/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"static/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"static/js/metisMenu.min.js\"></script>\r\n");
      out.write("    <script src=\"static/js/simplebar.min.js\"></script>\r\n");
      out.write("    <script src=\"static/js/waves.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"static/js/bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Summernote js -->\r\n");
      out.write("    <script src=\"static/js/summernote-bs4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- init js -->\r\n");
      out.write("    <script src=\"static/js/summernote.init.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"static/js/app.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Plugin Js-->\r\n");
      out.write("    <script src=\"static/js/dataTables.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Page Js -->\r\n");
      out.write("    <script src=\"static/js/template.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t    function edit(obj,id,inventoryId){\r\n");
      out.write("\t        var $td= $(obj).parents('tr').children('td');\r\n");
      out.write("\t       \r\n");
      out.write("\t        var price = $td.eq(2).text().replace(/\\s*/g,\"\");\r\n");
      out.write("\t        var num = $td.eq(3).text().replace(/\\s*/g,\"\");\r\n");
      out.write("\t        //alert(tel);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t//var i= address.toString();\r\n");
      out.write("\t       \r\n");
      out.write("\t       $(\"#updateInventory\").val(inventoryId); \r\n");
      out.write("\t      //  $(\"#updateName\").css('color','red').val(\"qqq\"+tel);\r\n");
      out.write("\t      $(\"#updatePrice\").val(price);\r\n");
      out.write("\t        $(\"#updateNum\").val(num);\r\n");
      out.write("\t        $(\"#updateId\").val(id);\r\n");
      out.write("\t      //  $(\"#updateTel\").css('color','red').css('text-align','left');\r\n");
      out.write("  \r\n");
      out.write("\t    }    \r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // project data table\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $('#myProjectTable')\r\n");
      out.write("                .addClass('nowrap')\r\n");
      out.write("                .dataTable({\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    columnDefs: [\r\n");
      out.write("                        { targets: [-1, -3], className: 'dt-body-right' }\r\n");
      out.write("                    ]\r\n");
      out.write("                });\r\n");
      out.write("            $('.deleterow').on('click', function () {\r\n");
      out.write("                var tablename = $(this).closest('table').DataTable();\r\n");
      out.write("                tablename\r\n");
      out.write("                    .row($(this)\r\n");
      out.write("                        .parents('tr'))\r\n");
      out.write("                    .remove()\r\n");
      out.write("                    .draw();\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
