/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-09 11:58:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxnu.util.Data;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxnu.util.Data");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>登录</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./style.css\" />\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    \t* {\r\n");
      out.write("\t\t  box-sizing: border-box;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\thtml {\r\n");
      out.write("\t\t  height: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t  background-color: #1E3B30;\r\n");
      out.write("\t\t  color: #7e8ba3;\r\n");
      out.write("\t\t  font: 300 1rem/1.5 Helvetica Neue, sans-serif;\r\n");
      out.write("\t\t  margin: 0;\r\n");
      out.write("\t\t  min-height: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.align {\r\n");
      out.write("\t\t  align-items: center;\r\n");
      out.write("\t\t  display: flex;\r\n");
      out.write("\t\t  flex-direction: row;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.align__item--start {\r\n");
      out.write("\t\t  align-self: flex-start;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.align__item--end {\r\n");
      out.write("\t\t  align-self: flex-end;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.site__logo {\r\n");
      out.write("\t\t  margin-bottom: 2rem;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinput {\r\n");
      out.write("\t\t  border: 0;\r\n");
      out.write("\t\t  font: inherit;\r\n");
      out.write("\t\t  font-family: \"微软雅黑\";\r\n");
      out.write("\t\t  color: white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinput::placeholder {\r\n");
      out.write("\t\t  color: #7e8ba3;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.form__field {\r\n");
      out.write("\t\t  margin-bottom: 1rem;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.form input {\r\n");
      out.write("\t\t  outline: 0;\r\n");
      out.write("\t\t  padding: 0.5rem 1rem;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.form input[type='email'],\r\n");
      out.write("\t\t.form input[type='password'] {\r\n");
      out.write("\t\t  width: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.grid {\r\n");
      out.write("\t\t  margin: 0 auto;\r\n");
      out.write("\t\t  max-width: 25rem;\r\n");
      out.write("\t\t  width: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\th2 {\r\n");
      out.write("\t\t  font-size: 2.75rem;\r\n");
      out.write("\t\t  font-weight: 100;\r\n");
      out.write("\t\t  margin: 0 0 1rem;\r\n");
      out.write("\t\t  text-transform: uppercase;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsvg {\r\n");
      out.write("\t\t  height: auto;\r\n");
      out.write("\t\t  max-width: 100%;\r\n");
      out.write("\t\t  vertical-align: middle;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ta {\r\n");
      out.write("\t\t  color: #7e8ba3;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.register {\r\n");
      out.write("\t\t  box-shadow: 0 0 250px #000;\r\n");
      out.write("\t\t  text-align: center;\r\n");
      out.write("\t\t  padding: 4rem 2rem;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.register input {\r\n");
      out.write("\t\t  border: 1px solid #44876D;\r\n");
      out.write("\t\t  border-radius: 999px;\r\n");
      out.write("\t\t  background-color: transparent;\r\n");
      out.write("\t\t  text-align: center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t.register input[type='password'] {\r\n");
      out.write("\t\t  background-repeat: no-repeat;\r\n");
      out.write("\t\t  background-size: 1.5rem;\r\n");
      out.write("\t\t  background-position: 1rem 50%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/* .register input[type='email'] {\r\n");
      out.write("\t\t  background-image: url('data:image/svg+xml;\r\n");
      out.write("\t\t charset=UTF-8,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\" fill=\"#242c37\"><path d=\"M256.017 273.436l-205.17-170.029h410.904l-205.734 170.029zm-.034 55.462l-205.983-170.654v250.349h412v-249.94l-206.017 170.245z\"/></svg>');\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t.register input[type='password'] {\r\n");
      out.write("\t\t  background-image: url('data:image/svg+xml;\r\n");
      out.write("\t\t charset=UTF-8,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\" fill=\"#242c37\"><path d=\"M195.334 223.333h-50v-62.666c0-61.022 49.645-110.667 110.666-110.667 61.022 0 110.667 49.645 110.667 110.667v62.666h-50v-62.666c0-33.452-27.215-60.667-60.667-60.667-33.451 0-60.666 27.215-60.666 60.667v62.666zm208.666 30v208.667h-296v-208.667h296zm-121 87.667c0-14.912-12.088-27-27-27s-27 12.088-27 27c0 7.811 3.317 14.844 8.619 19.773 4.385 4.075 6.881 9.8 6.881 15.785v22.942h23v-22.941c0-5.989 2.494-11.708 6.881-15.785 5.302-4.93 8.619-11.963 8.619-19.774z\"/></svg>');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.register input[type='submit'] {\r\n");
      out.write("\t\t  background-image: linear-gradient(160deg, #8ceabb 0%, #378f7b 100%);\r\n");
      out.write("\t\t  color: #fff;\r\n");
      out.write("\t\t  margin-bottom: 6rem;\r\n");
      out.write("\t\t  width: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("      <head>\r\n");
      out.write("        <meta charset=\"UTF-8\" />\r\n");
      out.write("        <title>后台登录</title>\r\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("      </head>\r\n");
      out.write("      <body class=\"align\">\r\n");
      out.write("        <div class=\"grid align__item\">\r\n");
      out.write("          <div class=\"register\">\r\n");
      out.write("            <svg\r\n");
      out.write("              xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              class=\"site__logo\"\r\n");
      out.write("              width=\"56\"\r\n");
      out.write("              height=\"84\"\r\n");
      out.write("              viewBox=\"77.7 214.9 274.7 412\"\r\n");
      out.write("            >\r\n");
      out.write("              <defs>\r\n");
      out.write("                <linearGradient id=\"a\" x1=\"0%\" y1=\"0%\" y2=\"0%\">\r\n");
      out.write("                  <stop offset=\"0%\" stop-color=\"#8ceabb\" />\r\n");
      out.write("                  <stop offset=\"100%\" stop-color=\"#378f7b\" />\r\n");
      out.write("                </linearGradient>\r\n");
      out.write("              </defs>\r\n");
      out.write("              <path\r\n");
      out.write("                fill=\"url(#a)\"\r\n");
      out.write("                d=\"M215 214.9c-83.6 123.5-137.3 200.8-137.3 275.9 0 75.2 61.4 136.1 137.3 136.1s137.3-60.9 137.3-136.1c0-75.1-53.7-152.4-137.3-275.9z\"\r\n");
      out.write("              />\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <h3>Manager Sign Up</h3>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"");
      out.print(Data.URL );
      out.write("/managelogin?OP=login\" method=\"post\" class=\"form\">\r\n");
      out.write("            \r\n");
      out.write("              <div class=\"form__field\">\r\n");
      out.write("                <span>账&nbsp;&nbsp;&nbsp;号：</span><input  style=\"width: 240px !important;\" type=\"text\" name=\"username\" />\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form__field\">\r\n");
      out.write("                <span>密&nbsp;&nbsp;&nbsp;码：</span><input  style=\"width: 240px !important;\" type=\"password\"  name=\"password\" />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form__field\">\r\n");
      out.write("                <span>验证码：</span><input type=\"text\"   style=\"width: 160px !important;\" name=\"checkcode\" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                <img alt=\"\" src=\"");
      out.print(Data.URL );
      out.write("/checkcode\" onclick=\"this.src = this.src +'?'\">\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form__field\">\r\n");
      out.write("                <input type=\"submit\" style=\"color: #fff !important;width: 160px !important;font-weight: bold\" value=\"登 录\" />\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </body>\r\n");
      out.write("    </html>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
