/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-11 01:18:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import com.gxnu.util.Data;
import com.gxnu.entity.Schedule;
import com.gxnu.service.imp.ScheduleService;
import com.gxnu.service.IScheduleService;
import com.gxnu.entity.Unit;
import com.gxnu.service.imp.UnitService;
import com.gxnu.service.IUnitService;
import com.gxnu.entity.Doctor;
import com.gxnu.service.imp.DoctorService;
import com.gxnu.service.IDoctorService;
import com.gxnu.entity.Unit;
import com.gxnu.service.imp.UnitService;
import com.gxnu.service.IUnitService;

public final class Schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gxnu.entity.Schedule");
    _jspx_imports_classes.add("com.gxnu.service.imp.ScheduleService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gxnu.util.Data");
    _jspx_imports_classes.add("com.gxnu.service.imp.DoctorService");
    _jspx_imports_classes.add("com.gxnu.entity.Unit");
    _jspx_imports_classes.add("com.gxnu.service.imp.UnitService");
    _jspx_imports_classes.add("com.gxnu.entity.Doctor");
    _jspx_imports_classes.add("com.gxnu.service.IDoctorService");
    _jspx_imports_classes.add("com.gxnu.service.IUnitService");
    _jspx_imports_classes.add("com.gxnu.service.IScheduleService");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	    //直接获取数据库信息，显示出界面
	    IScheduleService iis = new ScheduleService();
		List<Schedule> schedules1 = new ArrayList<Schedule>();

		List<Schedule> schedules2 = new ArrayList<Schedule>();
		
		/*
		Object obj = request.getAttribute(Data.UNIT);
		Unit selectedUnit = new Unit();
		if (obj != null) {
			selectedUnit = (Unit) obj;
		}
		int selectedUnitId = selectedUnit.getId();
		*/
		
		int selectedUnitId =0;
		//Object obj = request.getAttribute("unitId");
		Object obj = session.getAttribute("unitId");
		if (obj != null) {
			selectedUnitId = (int) obj;
		}
		
		IDoctorService ids = new DoctorService();
		List<Doctor> doctors = ids.findByUnit(selectedUnitId);
		

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>值班管理 </title>\r\n");
      out.write("    <!-- plugin css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(Data.URL);
      out.write("/Manage/static/css/main.min.css\">\r\n");
      out.write("    <!-- project css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(Data.URL);
      out.write("/Manage/static/css/ihealth.style.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"ihealth-layout\" class=\"theme-tradewind\">\r\n");
      out.write("    <!-- main body area -->\r\n");
      out.write("    <div class=\"main px-lg-4 px-md-4\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Body: Body -->\r\n");
      out.write("        <div class=\"body d-flex py-lg-3 py-md-2\">\r\n");
      out.write("            <div class=\"container-xxl\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"border-0 mb-4\">\r\n");
      out.write("                        <div class=\"card-header py-3 no-bg bg-transparent d-flex align-items-center px-0 justify-content-between border-bottom\">\r\n");
      out.write("                            <h3 class=\"fw-bold mb-0\">值班管理</h3>    \r\n");
      out.write("                            <div class=\"col-auto d-flex\">\r\n");
      out.write("                           <!-- 添加排班按钮 data-bs-target=\"#addevent\"-->\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#addevent\">\r\n");
      out.write("                                <i class=\"icofont-plus-circle me-2 fs-6\"></i>添加排班</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> <!-- Row end  -->\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Doctor Calendar Area -->\r\n");
      out.write("        <section class=\"doctor-calendar-area section\" >\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>值班表</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"doctor-calendar-table table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr style=\"background-color: #6AAB9C;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Time</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Monday</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Tuesday</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Wednesday</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Thursday</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Friday</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Saturday</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Sunday</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t<form  id=\"updateForm\" method=\"post\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody style=\"padding: 12px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><span class=\"time\">上午</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

											
											//循环遍历集合，每循环一次，生成一行html<tr></tr>，在每一个单元格中 <td></td>,把静态数据改成数据库表中的记录
											
													for (int i=1;i<=7;i++){
														
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 
														schedules1 = iis.find(i, "上午",selectedUnitId);
														
														for(Schedule schedule1:schedules1){
															String selectName = "updateDoctorM"+ String.valueOf(i)+String.valueOf(schedule1.getId());
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"");
      out.print(selectName );
      out.write("\" id=\"");
      out.print(selectName );
      out.write("\" class=\"form-control\" style=\"width: 80%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

															
															for(Doctor doctor1 : doctors){
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=");
      out.print(doctor1.getId() );
if(doctor1.getId()==schedule1.getDoctor().getId()){ out.print("selected='selected'");} 
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(doctor1.getName() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t   <button type=\"button\" class=\"btn btn-outline-secondary\"   \r\n");
      out.write("                                                            \t\tonclick=\"edit(");
      out.print(schedule1.getId() );
      out.write(',');
      out.write('\'');
      out.print(selectName );
      out.write("')\">\r\n");
      out.write("                                                           \t\t\t <i class=\"icofont-edit text-success\"></i>\r\n");
      out.write("                                                         \t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style=\"align-content: center;\">");
      out.print(schedule1.getDoctor().getTel() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t                            <div class=\"col-auto d-flex\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t                             \r\n");
      out.write("\t\t\t\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t\t                           \t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t                           \t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><span class=\"time\">下午</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

											
											//循环遍历集合，每循环一次，生成一行html<tr></tr>，在每一个单元格中 <td></td>,把静态数据改成数据库表中的记录
											
													for (int i=1;i<=7;i++){
														
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 
														schedules2 = iis.find(i, "下午",selectedUnitId);
														for(Schedule schedule2:schedules2){
															String selectName = "updateDoctorA"+ String.valueOf(i)+String.valueOf(schedule2.getId());
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"");
      out.print(selectName );
      out.write("\" id=\"");
      out.print(selectName );
      out.write("\" class=\"form-control\" style=\"width: 80%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

															
															for(Doctor doctor2 : doctors){
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=");
      out.print(doctor2.getId() );
      out.write(' ');
if(doctor2.getId()==schedule2.getDoctor().getId()){ out.print("selected='selected'");} 
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(doctor2.getName() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t <button type=\"button\" class=\"btn btn-outline-secondary\"   \r\n");
      out.write("\t                                                  \t\tonclick=\"edit(");
      out.print(schedule2.getId() );
      out.write(',');
      out.write('\'');
      out.print(selectName );
      out.write("')\">\r\n");
      out.write("\t                                                 \t\t<i class=\"icofont-edit text-success\"></i>\r\n");
      out.write("                                               \t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span style=\"align-content: center;\">");
      out.print(schedule2.getDoctor().getTel() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                            <div class=\"col-auto d-flex\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                               \r\n");
      out.write("                                                         \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t\t\t                           \t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t                           \t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- End Doctor Calendar Area -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");

//String addUrl = Data.URL+"/schedule?OP=add&unitId="+selectedUnitId;
String addUrl = Data.URL+"/schedule?OP=add";

      out.write("\r\n");
      out.write("<!-- 点击添加“排班按钮”后 跳转到这 -->\r\n");
      out.write("        <!-- Add Event-->\r\n");
      out.write("        <div class=\"modal fade\" id=\"addevent\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("\t        <form  id=\"addForm\" method=\"post\" action=");
      out.print(addUrl );
      out.write(">\r\n");
      out.write("\t           \t <div class=\"modal-dialog modal-dialog-centered modal-md modal-dialog-scrollable\">\r\n");
      out.write("\t\t            <div class=\"modal-content\">\r\n");
      out.write("\t\t                <div class=\"modal-header\">\r\n");
      out.write("\t\t                    <h5 class=\"modal-title  fw-bold\" id=\"eventaddLabel\">添加排班</h5>\r\n");
      out.write("\t\t                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t                <div class=\"modal-body\">\r\n");
      out.write("\t\t                    <div class=\"mb-3\">\r\n");
      out.write("\t\t                        <label for=\"exampleFormControlInput99\" class=\"form-label\">值班医生</label>\r\n");
      out.write("\t\t                        \t<div> \r\n");
      out.write("\t                \t\t\t\t\t<select name=\"addDoctor\" id=\"addDoctor\" class=\"form-control\" style=\"width: 30%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											for(Doctor doctor3 : doctors){
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=");
      out.print(doctor3.getId() );
      out.write('>');
      out.print(doctor3.getName() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t           \t\t\t\t\t </div>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                    <div class=\"deadline-form\">\r\n");
      out.write("\t\t                            <div class=\"row g-3 mb-3\">\r\n");
      out.write("\t\t                              <div class=\"col\">\r\n");
      out.write("\t\t                                <label for=\"updatepickerded\" class=\"form-label\">值班周天</label>\r\n");
      out.write("\t\t                                 <div> \r\n");
      out.write("\t\t                \t\t\t\t\t<select name=\"addWeek\" id=\"addWeek\" class=\"form-control\" style=\"width: 30%;\">\r\n");
      out.write("\t\t\t\t\t                            <option value=\"1\">周一</option>\r\n");
      out.write("\t\t\t\t\t                            <option value=\"2\">周二</option>\r\n");
      out.write("\t\t\t\t\t                            <option value=\"3\">周三</option>\r\n");
      out.write("\t\t\t\t\t                            <option value=\"4\">周四</option>\r\n");
      out.write("\t\t\t\t\t                            <option value=\"5\">周五</option>\r\n");
      out.write("\t\t\t\t\t                            <option value=\"6\">周六</option>\r\n");
      out.write("\t\t\t\t\t                            <option value=\"7\">周日</option>\r\n");
      out.write("\t\t                        \t\t\t</select>\r\n");
      out.write("\t\t           \t\t\t\t\t\t </div>\r\n");
      out.write("\t\t                                \r\n");
      out.write("\t\t                                \r\n");
      out.write("\t\t                                \r\n");
      out.write("\t\t                              </div>\r\n");
      out.write("\t\t                               <div class=\"col\">\r\n");
      out.write("\t\t                                <label for=\"datepickerdedone\" class=\"form-label\">值班时段</label>\r\n");
      out.write("\t\t                                  <div> \r\n");
      out.write("\t\t                \t\t\t\t\t<select name=\"addPeriod\" id=\"addperiod\" class=\"form-control\" style=\"width: 30%;\">\r\n");
      out.write("\t\t\t\t\t                            <option >上午</option>\r\n");
      out.write("\t\t\t\t\t                            <option >下午</option>\r\n");
      out.write("\t\t                        \t\t\t</select>\r\n");
      out.write("\t\t           \t\t\t\t\t \t</div>\r\n");
      out.write("\t\t                              </div>\r\n");
      out.write("\t\t                              \r\n");
      out.write("\t\t                          <div class=\"col\">\r\n");
      out.write("\t                                <label for=\"datepickerded\" class=\"form-label\">值班开始日期</label>\r\n");
      out.write("\t                                <input name=\"addTime\" id=\"addTime\" type=\"date\" class=\"form-control\" id=\"datepickerded\">\r\n");
      out.write("\t                              </div>\r\n");
      out.write("\t                              \r\n");
      out.write("\t\t                            </div>   \r\n");
      out.write("\t\t                            \r\n");
      out.write("\t\t                  \t  </div>\t\r\n");
      out.write("\t\t                  \t  \r\n");
      out.write("\t\t\t                    <div class=\"mb-3\">\r\n");
      out.write("\t\t\t                        <label for=\"exampleFormControlTextarea78\" class=\"form-label\">内容描述（可省略）</label>\r\n");
      out.write("\t\t\t                        <textarea class=\"form-control\" id=\"exampleFormControlTextarea78\" rows=\"3\" placeholder=\"Add any extra details about the request\"></textarea>\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t                <!-- 按钮 -->\r\n");
      out.write("\t\t                <div class=\"modal-footer\">\r\n");
      out.write("\t\t                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">关闭</button>\r\n");
      out.write("                            <input type=\"button\" class=\"btn btn-primary\" onclick=\"tjAdd()\" value=\"添加\"/>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t           \t</form>\r\n");
      out.write("            \t\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("        // project data table\r\n");
      out.write("       // $(\"#depedit\").modal(\"hide\");\r\n");
      out.write("       //第一种 无用\r\n");
      out.write("        function Values(ID){//在按钮中定义的点击事件函数Values,传入ID\r\n");
      out.write("          //  alert(ID);\r\n");
      out.write("\t\t\t$(\"#id\").val(ID); //接收传入的ID值,发送给id为id的标签\r\n");
      out.write("\t\t\t\r\n");
      out.write("            }\r\n");
      out.write("\t\t//第二种\r\n");
      out.write("\r\n");
      out.write("        function edit(id,selectName){\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("        \tconsole.log(\"");
      out.print(Data.URL);
      out.write("/schedule?OP=update&updateId=\"+id+\"&selectName=\"+selectName);\r\n");
      out.write("        \tdocument.getElementById(\"updateForm\").action=\"");
      out.print(Data.URL);
      out.write("/schedule?OP=update&updateId=\"+id+\"&selectName=\"+selectName;\r\n");
      out.write("        \t\r\n");
      out.write("        \twindow.document.getElementById(\"updateForm\").submit();\r\n");
      out.write("        \talert(\"修改成功\");\r\n");
      out.write("        \t\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        function remove(url){//在按钮中定义的点击事件函数remove\r\n");
      out.write("\r\n");
      out.write("        \t//console.log(url);//测试\r\n");
      out.write("          \twindow.location.href=url;//跳转\r\n");
      out.write("  \t\t\t\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("    \tfunction tjAdd() {\r\n");
      out.write("    \t\t//根据id获取html页面中的表单，并提交\r\n");
      out.write("    \t\twindow.document.getElementById(\"addForm\").submit();\r\n");
      out.write("    \t}\r\n");
      out.write("\r\n");
      out.write("    \tfunction tjUpdate() {\r\n");
      out.write("    \t\t//根据id获取html页面中的表单，并提交\r\n");
      out.write("    \t\twindow.document.getElementById(\"updateForm\").submit();\r\n");
      out.write("    \t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Core Js -->\r\n");
      out.write("<script src=\"");
      out.print(Data.URL);
      out.write("/Manage/static/js/libscripts.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin Js-->\r\n");
      out.write("<script src=\"");
      out.print(Data.URL);
      out.write("/Manage/static/js/main.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery Page Js -->\r\n");
      out.write("<script src=\"");
      out.print(Data.URL);
      out.write("/Manage/static/js/template.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
