/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2022-08-11 01:18:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import com.gxnu.util.Data;
import com.gxnu.entity.Unit;
import com.gxnu.service.imp.UnitService;
import com.gxnu.service.IUnitService;

public final class Unit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.gxnu.util.Data");
    _jspx_imports_classes.add("com.gxnu.entity.Unit");
    _jspx_imports_classes.add("com.gxnu.service.imp.UnitService");
    _jspx_imports_classes.add("com.gxnu.service.IUnitService");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String url = Data.URL+"/unit"; 
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>科室管理</title>\r\n");
      out.write("    <!-- Summernote css -->\r\n");
      out.write("    <link href=\"static/css/summernote-bs4.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <!-- plugin css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/responsive.dataTables.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/dataTables.bootstrap5.min.css\">\r\n");
      out.write("    <!-- project css file  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/css/ihealth.style.min.css\">\r\n");
      out.write("    <!-- Bootstrap Css -->\r\n");
      out.write("    <link href=\"static/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <!-- Icons Css -->\r\n");
      out.write("    <link href=\"static/css/icons.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <!-- App Css-->\r\n");
      out.write("    <link href=\"static/css/app.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"ihealth-layout\" class=\"theme-tradewind\">\r\n");
      out.write("\r\n");
      out.write("        <!-- sidebar -->\r\n");
      out.write("       \r\n");
      out.write("        <!-- main body area -->\r\n");
      out.write("        <div class=\"main px-lg-4 px-md-4\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Body: Header -->\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <!-- Body: Body -->\r\n");
      out.write("            <div class=\"body d-flex py-lg-3 py-md-2\">\r\n");
      out.write("                <div class=\"container-xxl\">\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"border-0 mb-4\">\r\n");
      out.write("                            <div\r\n");
      out.write("                                class=\"card-header py-3 no-bg bg-transparent d-flex align-items-center px-0 justify-content-between border-bottom flex-wrap\">\r\n");
      out.write("                                <h3 class=\"fw-bold mb-0\">科室管理</h3>\r\n");
      out.write("                                <div class=\"col-auto d-flex w-sm-100\">\r\n");
      out.write("                                <!-- 添加按钮 data-bs-target=\"#depadd\"跳转-->\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-primary btn-set-task w-sm-100\"\r\n");
      out.write("                                        data-bs-toggle=\"modal\" data-bs-target=\"#depadd\"><i\r\n");
      out.write("                                            class=\"icofont-plus-circle me-2 fs-6\"></i>添加</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> <!-- Row end  -->\r\n");
      out.write("                    <div class=\"row clearfix g-3\">\r\n");
      out.write("                        <div class=\"col-sm-12\">\r\n");
      out.write("                            <div class=\"card mb-3\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <table id=\"myProjectTable\" class=\"table table-hover align-middle mb-0\"\r\n");
      out.write("                                        style=\"width:100%\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th scope=\"col\">id</th>\r\n");
      out.write("                                                <th scope=\"col\">科室名称</th>\r\n");
      out.write("                                                <th scope=\"col\">科室地点</th>\r\n");
      out.write("                                                <th scope=\"col\">负责人</th>\r\n");
      out.write("                                                <th scope=\"col\">负责人联系电话</th>\r\n");
      out.write("                                                <th scope=\"col\">基本操作</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

										
										    //直接获取数据库信息，显示出界面
										    IUnitService ius = new UnitService();
											List<Unit> units = new ArrayList<Unit>();
											units = ius.findAll();
											int i = 1;
											for(Unit unit:units){
													
											
      out.write("                                      \t\r\n");
      out.write("                                            <tr><!-- 按钮所在的tr -->\r\n");
      out.write("                                                <td><!-- 按钮所在的tr的孩子td 然后用eq选择器，索引是从0开始，可以取对应list列表的值-->\r\n");
      out.write("                                                    <span class=\"fw-bold\">");
      out.print(i );
      out.write("</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    ");
      out.print(unit.getName() );
      out.write("\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                \r\n");
      out.write("                                                \r\n");
      out.write("                                                <td>\r\n");
      out.write("\r\n");
      out.write("                                                   ");
      out.print(unit.getAddress() );
      out.write("\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                   ");
      out.print(unit.getPrincipal() );
      out.write("\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                   ");
      out.print(unit.getTel() );
      out.write("\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div class=\"btn-group\" role=\"group\"  aria-label=\"Basic outlined example\">\r\n");
      out.write("                                                    \r\n");
      out.write("                                                    <!-- 编辑按钮——>数据回显 -->\r\n");
      out.write("                                                     <!-- 第一种\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle: 以什么事件触发，如modal,popover,tooltips等；\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-target: 事件的目标；\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t1、Bootstrap 模态框带参数传值实例: https://blog.csdn.net/linhaiyun_ytdx/article/details/77417702 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t2、onclick点击事件实现向其传值\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"Values(");
      out.print(unit.getId() );
      out.write(")\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!--第二种\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t先给按钮绑定一个onclick事件，然后点击按钮触发edit(this)事件。\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t this是当前button标签 找他的父标签tr的孩子标签th。然后用eq选择器，索引是从0开始，可以取对应list列表的值。\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t 然后用JQuery，把数据渲染到对应的ID里。\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t https://blog.csdn.net/zlq0527/article/details/114804760\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t -->\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-outline-secondary\"\r\n");
      out.write("                                                            data-bs-toggle=\"modal\" data-bs-target=\"#depedit\" \r\n");
      out.write("                                                            onclick=\"edit(this,");
      out.print(unit.getId() );
      out.write(")\">\r\n");
      out.write("                                                            <i class=\"icofont-edit text-success\"></i>\r\n");
      out.write("                                                         </button>\r\n");
      out.write("                                                            \r\n");
      out.write("                                                            <!--  onclick=\"window.location.href='https://www.bilibili.com/'\" > -->\r\n");
      out.write("                                                            \r\n");
      out.write("                                                            <!-- 跳转url -->\r\n");
      out.write("                                                     ");
String removeUrl = Data.URL+"/unit?id=" +unit.getId();
      out.write("       \r\n");
      out.write("                                                     <!-- 删除按钮 -->\r\n");
      out.write("                                                        <button type=\"button\"  class=\"btn btn-outline-secondary \"\r\n");
      out.write("                                                         onclick=\"remove('");
      out.print(removeUrl );
      out.write("')\" >\r\n");
      out.write("                                                        \t<i class=\"icofont-ui-delete text-danger\"></i>\r\n");
      out.write("                                                        </button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                \r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            ");
i++;} 
      out.write("\r\n");
      out.write("                                          \r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div><!-- Row End -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Modal Custom Settings-->\r\n");
      out.write("\r\n");

String addUrl=url+ "?OP=add";

      out.write("\r\n");
      out.write("            <!-- 添加科室信息-->\r\n");
      out.write("            <div class=\"modal fade\" id=\"depadd\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-centered modal-md modal-dialog-scrollable\">\r\n");
      out.write("                  \r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h5 class=\"modal-title  fw-bold\" id=\"depaddLabel\">添加科室信息</h5>\r\n");
      out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"deadline-form\">\r\n");
      out.write("                              <form id=\"addForm\" method=\"post\" action=");
      out.print(addUrl );
      out.write(">\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"depone\" class=\"form-label\">科室名称</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"addName\" name=\"addName\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"depone\" class=\"form-label\">科室地点</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"addAddress\" name=\"addAddress\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"deptwo\" class=\"form-label\">负责人</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"addPrincipal\" name=\"addPrincipal\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("                                        <label for=\"deptwo\" class=\"form-label\">负责人联系电话</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"addTel\" name=\"addTel\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">取消</button>\r\n");
      out.write("                            <input type=\"button\" class=\"btn btn-primary\" onclick=\"tjAdd()\" value=\"添加\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");

String updateUrl = url +"?OP=update";

      out.write("\r\n");
      out.write("            <!-- 编辑科室信息-->\r\n");
      out.write("            <div class=\"modal fade\" id=\"depedit\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-centered modal-md modal-dialog-scrollable\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h5 class=\"modal-title  fw-bold\" id=\"depeditLabel\"> 编辑科室信息</h5>\r\n");
      out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"deadline-form\">\r\n");
      out.write("                                <form id=\"updateForm\" method=\"post\" action=");
      out.print(updateUrl );
      out.write(">\r\n");
      out.write("                                    <div class=\"col-sm-6\" style=\"max-width: 100%\">\r\n");
      out.write("                                        <label for=\"depone\" class=\"form-label\">科室名称</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"updateName\" name=\"updateName\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\" style=\"max-width: 100%\">\r\n");
      out.write("                                        <label for=\"depone\" class=\"form-label\">科室地点</label>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"updateAddress\" name=\"updateAddress\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\" style=\"max-width: 100%\">\r\n");
      out.write("                                        <label for=\"deptwo\" class=\"form-label\">负责人</label>\r\n");
      out.write("                                        <input  type=\"text\" class=\"form-control\" id=\"updatePrincipal\" name=\"updatePrincipal\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-6\" style=\"max-width: 100%\">\r\n");
      out.write("                                        <label for=\"deptwo\" class=\"form-label\">负责人联系电话</label>\r\n");
      out.write("                                        <input style=\"width:100%\"  type=\"text\" class=\"form-control\" id=\"updateTel\"  name=\"updateTel\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" id=\"updateId\" name=\"updateId\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">取消</button>\r\n");
      out.write("                            <input type=\"button\" class=\"btn btn-primary\"  onclick=\"tjUpdate()\" value=\"保存\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Core Js -->\r\n");
      out.write("    <script src=\"static/js/libscripts.bundle.js\"></script>\r\n");
      out.write("    <!-- JAVASCRIPT -->\r\n");
      out.write("    <script src=\"static/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"static/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"static/js/metisMenu.min.js\"></script>\r\n");
      out.write("    <script src=\"static/js/simplebar.min.js\"></script>\r\n");
      out.write("    <script src=\"static/js/waves.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"static/js/bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Summernote js -->\r\n");
      out.write("    <script src=\"static/js/summernote-bs4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- init js -->\r\n");
      out.write("    <script src=\"static/js/summernote.init.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"static/js/app.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Plugin Js-->\r\n");
      out.write("    <script src=\"static/js/dataTables.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Jquery Page Js -->\r\n");
      out.write("    <script src=\"static/js/template.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // project data table\r\n");
      out.write("       // $(\"#depedit\").modal(\"hide\");\r\n");
      out.write("       //第一种 无用\r\n");
      out.write("        function Values(ID){//在按钮中定义的点击事件函数Values,传入ID\r\n");
      out.write("          //  alert(ID);\r\n");
      out.write("\t\t\t$(\"#id\").val(ID); //接收传入的ID值,发送给id为id的标签\r\n");
      out.write("\t\t\t\r\n");
      out.write("            }\r\n");
      out.write("\t\t//第二种\r\n");
      out.write("        function edit(obj,id){\r\n");
      out.write("            var $td= $(obj).parents('tr').children('td');\r\n");
      out.write("           \r\n");
      out.write("            var name = $td.eq(1).text();\r\n");
      out.write("            var address = $td.eq(2).text();\r\n");
      out.write("            var principal = $td.eq(3).text();\r\n");
      out.write("            var tel = $td.eq(4).text();\r\n");
      out.write("            //alert(tel);\r\n");
      out.write("\r\n");
      out.write("\t\t\t//var i= address.toString();\r\n");
      out.write("           \r\n");
      out.write("            $(\"#updateId\").val(id); \r\n");
      out.write("          //  $(\"#updateName\").css('color','red').val(\"qqq\"+tel);\r\n");
      out.write("          $(\"#updateName\").val(name);\r\n");
      out.write("            $(\"#updateAddress\").val(address);\r\n");
      out.write("            $(\"#updatePrincipal\").val(principal);\r\n");
      out.write("          //  $(\"#updateTel\").css('color','red').css('text-align','left');\r\n");
      out.write("            $(\"#updateTel\").val(tel);\r\n");
      out.write("\t\t\t\r\n");
      out.write("            //控制台输出测试\r\n");
      out.write("            console.log(id.length);\r\n");
      out.write("            console.log(name);\r\n");
      out.write("            console.log(address);\r\n");
      out.write("            console.log(principal);\r\n");
      out.write("            console.log(tel);\r\n");
      out.write("          \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        function remove(url){//在按钮中定义的点击事件函数remove\r\n");
      out.write("\r\n");
      out.write("        \t//console.log(url);//测试\r\n");
      out.write("          \twindow.location.href=url;//跳转\r\n");
      out.write("  \t\t\t\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("    \tfunction tjAdd() {\r\n");
      out.write("    \t\t//根据id获取html页面中的表单，并提交\r\n");
      out.write("    \t\twindow.document.getElementById(\"addForm\").submit();\r\n");
      out.write("    \t}\r\n");
      out.write("\r\n");
      out.write("    \tfunction tjUpdate() {\r\n");
      out.write("    \t\t//根据id获取html页面中的表单，并提交\r\n");
      out.write("    \t\twindow.document.getElementById(\"updateForm\").submit();\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("        \r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $('#myProjectTable')\r\n");
      out.write("                .addClass('nowrap')\r\n");
      out.write("                .dataTable({\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    columnDefs: [\r\n");
      out.write("                        { targets: [-1, -3], className: 'dt-body-right' }\r\n");
      out.write("                    ]\r\n");
      out.write("                });\r\n");
      out.write("            $('.deleterow').on('click', function () {\r\n");
      out.write("                var tablename = $(this).closest('table').DataTable();\r\n");
      out.write("                tablename\r\n");
      out.write("                    .row($(this)\r\n");
      out.write("                        .parents('tr'))\r\n");
      out.write("                    .remove()\r\n");
      out.write("                    .draw();\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
